CREATE DATABASE streetlogix;

USE streetlogix;

CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(32) NOT NULL UNIQUE,
  password VARCHAR(32) NOT NULL,
  firstName VARCHAR(32) NOT NULL,
  lastName VARCHAR(32) NOT NULL,
  title VARCHAR(32) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  active BOOLEAN
);

CREATE TABLE invite_users (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(32) NOT NULL,
  lastName VARCHAR(32) NOT NULL,
  email VARCHAR(32) NOT NULL UNIQUE,
  title VARCHAR(32) NOT NULL,
  role VARCHAR(32) NOT NULL
);
